### ISSUE TITLE
Unknown system variable 'query_cache_size'

### ISSUE THREAD

**Issue by Mahesh-MSFT** [Azure-Samples/spring-data-jpa-on-azure#1]
I am following instructions to connect to Azure Database for MySQL (Version 8.0).

Getting following error when running `java -jar target/spring-data-jpa-on-azure-0.1.0-SNAPSHOT.jar`

`java.sql.SQLException: Unknown system variable 'query_cache_size'
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[mysql-connector-java-5.1.47.jar!/:5.1.47]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar!/:5.1.47]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar!/:5.1.47]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar!/:5.1.47]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar!/:5.1.47]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2491) ~[mysql-connector-java-5.1.47.jar!/:5.1.47]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2449) ~[mysql-connector-java-5.1.47.jar!/:5.1.47]
        at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1381) ~[mysql-connector-java-5.1.47.jar!/:5.1.47]`

What changes are needed to make this work?

**Comment by dingmeng-xue** [comment]
Thanks for reporting. I'm closing this issue before archiving this repo.
